// Cached DOM element references for the app shell and the Settings/Admin panel.
// Evaluated once at module load (the host script is a deferred module, so the
// DOM is parsed by then).

export const els = {
  tabs: document.querySelectorAll(".tab"),
  panels: document.querySelectorAll(".panel"),
  exportBtn: document.getElementById("exportBtn"),
  importInput: document.getElementById("importInput"),

  macroDate: document.getElementById("macroDate"),
  mealForm: document.getElementById("mealForm"),
  mealName: document.getElementById("mealName"),
  mealProtein: document.getElementById("mealProtein"),
  mealCarbs: document.getElementById("mealCarbs"),
  mealFats: document.getElementById("mealFats"),
  mealCalories: document.getElementById("mealCalories"),
  mealEntries: document.getElementById("mealEntries"),
  macroLockNote: document.getElementById("macroLockNote"),
  recentMeals: document.getElementById("recentMeals"),
  quickAddHead: document.getElementById("quickAddHead"),
  macroPrev: document.getElementById("macroPrev"),
  macroNext: document.getElementById("macroNext"),
  macroToday: document.getElementById("macroToday"),

  proteinMetric: document.getElementById("proteinMetric"),
  carbMetric: document.getElementById("carbMetric"),
  fatMetric: document.getElementById("fatMetric"),
  calorieMetric: document.getElementById("calorieMetric"),
  proteinValue: document.getElementById("proteinValue"),
  carbValue: document.getElementById("carbValue"),
  fatValue: document.getElementById("fatValue"),
  calorieValue: document.getElementById("calorieValue"),
  proteinRing: document.getElementById("proteinRing"),
  carbRing: document.getElementById("carbRing"),
  fatRing: document.getElementById("fatRing"),
  calorieRing: document.getElementById("calorieRing"),

  waterCount: document.getElementById("waterCount"),
  waterTrack: document.getElementById("waterTrack"),
  waterMl: document.getElementById("waterMl"),
  waterMinus: document.getElementById("waterMinus"),
  waterPlus: document.getElementById("waterPlus"),

  trendRangeSeg: document.getElementById("trendRangeSeg"),
  trendStats: document.getElementById("trendStats"),
  trendChart: document.getElementById("trendChart"),

  morningDate: document.getElementById("morningDate"),
  morningPrev: document.getElementById("morningPrev"),
  morningNext: document.getElementById("morningNext"),
  morningToday: document.getElementById("morningToday"),
  mealsMorning: document.getElementById("mealsMorning"),
  mealsEvening: document.getElementById("mealsEvening"),
  dayTypeBadge: document.getElementById("dayTypeBadge"),
  swapDayBtn: document.getElementById("swapDayBtn"),
  resetDayBtn: document.getElementById("resetDayBtn"),
  mealGroupSelect: document.getElementById("mealGroupSelect"),
  morningTaskForm: document.getElementById("morningTaskForm"),
  morningTaskInput: document.getElementById("morningTaskInput"),
  dailyLockNote: document.getElementById("dailyLockNote"),

  mealPrepWeek: document.getElementById("mealPrepWeek"),
  mealPrepChecklist: document.getElementById("mealPrepChecklist"),
  mealPrepTaskForm: document.getElementById("mealPrepTaskForm"),
  mealPrepTaskInput: document.getElementById("mealPrepTaskInput"),
  mealPrepLockNote: document.getElementById("mealPrepLockNote"),

  weeklySelect: document.getElementById("weeklySelect"),
  weeklyGroceryList: document.getElementById("weeklyGroceryList"),
  weeklyItemForm: document.getElementById("weeklyItemForm"),
  weeklyItemName: document.getElementById("weeklyItemName"),
  weeklyItemQty: document.getElementById("weeklyItemQty"),
  weeklyLockNote: document.getElementById("weeklyLockNote"),

  monthlySelect: document.getElementById("monthlySelect"),
  monthlyTableWrap: document.getElementById("monthlyTableWrap"),
  restockSummary: document.getElementById("restockSummary"),

  historyPrev: document.getElementById("historyPrev"),
  historyNext: document.getElementById("historyNext"),
  historyLabel: document.getElementById("historyLabel"),
  historySummary: document.getElementById("historySummary"),
  historyChart: document.getElementById("historyChart"),
  historyChartTitle: document.getElementById("historyChartTitle"),
  historyLegend: document.getElementById("historyLegend"),
  historyLegendDot: document.getElementById("historyLegendDot"),
  historyBreakdown: document.getElementById("historyBreakdown"),
  historyHint: document.getElementById("historyHint"),
  historyPeriodSeg: document.getElementById("historyPeriodSeg"),
  historyMetricSeg: document.getElementById("historyMetricSeg"),

  installBtn: document.getElementById("installBtn"),
  installBanner: document.getElementById("installBanner"),
  installDismiss: document.getElementById("installDismiss"),
  installBtn2: document.getElementById("installBtn2"),
  installHint: document.getElementById("installHint"),
  activePlanLabel: document.getElementById("activePlanLabel"),

  planInput: document.getElementById("planInput"),
  planStatus: document.getElementById("planStatus"),
  downloadPlanTemplateBtn: document.getElementById("downloadPlanTemplateBtn"),

  // Cloud sync (account-based, Cloudflare D1)
  cloudSignedOut: document.getElementById("cloudSignedOut"),
  cloudSignedIn: document.getElementById("cloudSignedIn"),
  authEmail: document.getElementById("authEmail"),
  authPassword: document.getElementById("authPassword"),
  apiBaseInput: document.getElementById("apiBaseInput"),
  signInBtn: document.getElementById("signInBtn"),
  registerBtn: document.getElementById("registerBtn"),
  signedInEmail: document.getElementById("signedInEmail"),
  autoSyncToggle: document.getElementById("autoSyncToggle"),
  syncNowBtn: document.getElementById("syncNowBtn"),
  signOutBtn: document.getElementById("signOutBtn"),
  syncStatus: document.getElementById("syncStatus"),

  exportBtn2: document.getElementById("exportBtn2"),
  importInput2: document.getElementById("importInput2"),
};

export const adminEls = {
  openBtn: document.getElementById("openAdminBtn"),
  closeBtn: document.getElementById("closeAdminBtn"),

  subTabs: [...document.querySelectorAll("#adminSubNav .admin-subtab")],
  subPanels: [...document.querySelectorAll(".admin-subpanel")],

  targetProtein: document.getElementById("adminTargetProtein"),
  targetCarbs: document.getElementById("adminTargetCarbs"),
  targetFats: document.getElementById("adminTargetFats"),
  targetCalories: document.getElementById("adminTargetCalories"),
  saveTargetsBtn: document.getElementById("saveTargetsBtn"),
  resetTargetsBtn: document.getElementById("resetTargetsBtn"),
  targetsStatus: document.getElementById("adminTargetsStatus"),

  dayTypeSeg: document.getElementById("adminDayTypeSeg"),
  dailyRows: document.getElementById("adminDailyRows"),
  dailyAddBtn: document.getElementById("adminDailyAddBtn"),
  saveDailyBtn: document.getElementById("saveDailyBtn"),
  resetDailyBtn: document.getElementById("resetDailyBtn"),
  dailyStatus: document.getElementById("adminDailyStatus"),

  weeklyPrepRows: document.getElementById("adminWeeklyPrepRows"),
  weeklyPrepAddBtn: document.getElementById("adminWeeklyPrepAddBtn"),
  saveWeeklyPrepBtn: document.getElementById("saveWeeklyPrepBtn"),
  resetWeeklyPrepBtn: document.getElementById("resetWeeklyPrepBtn"),
  weeklyPrepStatus: document.getElementById("adminWeeklyPrepStatus"),

  weekSelect: document.getElementById("adminWeekSelect"),
  weeklyGroceryRows: document.getElementById("adminWeeklyGroceryRows"),
  weeklyGroceryAddBtn: document.getElementById("adminWeeklyGroceryAddBtn"),
  saveWeeklyGroceryBtn: document.getElementById("saveWeeklyGroceryBtn"),
  resetWeeklyGroceryBtn: document.getElementById("resetWeeklyGroceryBtn"),
  weeklyGroceryStatus: document.getElementById("adminWeeklyGroceryStatus"),

  monthlyRows: document.getElementById("adminMonthlyRows"),
  monthlyAddBtn: document.getElementById("adminMonthlyAddBtn"),
  saveMonthlyBtn: document.getElementById("saveMonthlyBtn"),
  resetMonthlyBtn: document.getElementById("resetMonthlyBtn"),
  monthlyStatus: document.getElementById("adminMonthlyStatus"),

  resetAllBtn: document.getElementById("resetAllDefaultsBtn"),
  resetAllStatus: document.getElementById("adminResetAllStatus"),

  modal: document.getElementById("adminModal"),
  modalTitle: document.getElementById("adminModalTitle"),
  modalBody: document.getElementById("adminModalBody"),
  modalApply: document.getElementById("adminModalApply"),
  modalDismiss: document.getElementById("adminModalDismiss"),
};
